name: Sign Executable and Create Release

on:
  push:
    tags:
      - 'v*' # runs when you push a version tag like v1.0.0
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., v1.0.0)'
        required: true
        default: 'v0.1.0'
      file_path:
        description: 'Path to executable file'
        required: true
        default: 'assets/exe/Aukaat_0.1.0_x64-setup.exe'
jobs:
  sign-and-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: upload-unsigned-artifact
      id: upload-unsigned-artifact
      uses: actions/upload-artifact@v4
      with:
        path: 'assets/exe/Aukaat_0.1.0_x64-setup.exe'

    - id: signing-the-exe
      uses: signpath/github-action-submit-signing-request@v1.1
      with:
        organization-id: ${{ secrets.SIGNPATH_ORG_ID }}
        project-slug: ${{ secrets.SIGNPATH_PROJECT_ID }}
        api-token: ${{ secrets.SIGNPATH_TOKEN }}
        signing-policy-slug: 'default'
        github-artifact-id: '${{ steps.upload-unsigned-artifact.outputs.artifact-id }}'
        wait-for-completion: true
        output-artifact-directory: './signed-artifacts'